
/**
  * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  * ! WARNING: This is a generated file, any modifications may be overwritten !
  * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  *
  * Generated by "merge2file"
  *
  * Date: Tue Dec 12 2017 18:10:05 GMT+0100 (CET)
  * Export target: "./src/languages/export/es.js"
  * Executor: dufourd
  * Duration: 1 ms.
*/
const es = {
  flow: {
    base: "Asistente de página",
    layout: "Disposición",
    model: "Modelo",
    page: "Página"
  },
  pageType: {
    layout: "Disposición",
    model: "Modelo"
  },
  stepLabel: {
    base: "¿Desea crear una página desde un \"{0}\" o \"{1}\" ?",
    chooseCreate: "Elegir o crear \"{0}\"",
    createNew: "Creando \"{0}\"",
    back: "Devolución de un paso",
    done: "Done"
  },
  stepButton: {
    createPage: "Crear y Editar",
    done: "Crear otro",
    next: "Próximo",
    back: "Regreso"
  },
  modal: {
    yes: "Si",
    no: "No",
    cancel: "anular",
    confirm: "confirmar",
    edit: "Antes de pasar al siguiente paso, ¿quiere \"{0}\" ?"
  },
  inputNew: "Encabezado \"{0}\"",
  optionChoose: "Elegir",
  insertTitle: "Ingrese un título para {0} \"{1}\""
};
module.exports = es;